ballot_date = 2021-11-28

[mode.aargau]
n = 8000
invitation = [ "online" ]
reminder = [ "online", "print" ]
[mode.aargau.postal_dispatch.type]
invitation = "B bulk mailing"
reminder = "B bulk mailing"
prepaid_reply_envelope = "B"
[mode.aargau.postal_dispatch.date]
invitation = 2021-11-22
reminder = 2021-12-01


[url]
federal.booklet = "https://www.admin.ch/dam/gov/de/Dokumentation/Abstimmungen/November2021/Abstimmungsbroschuere_28-11-2021_de.pdf.download.pdf/Abstimmungsbroschuere_28-11-2021_de.pdf"
cantonal.archive = "https://www.ag.ch/de/aktuelles/wahlen_und_abstimmungen/abstimmungen/vorschau/vorschau_details/vorschau_details_168396.jsp"


[federal.proposal.1]
type = "citizens' initiative"
[federal.proposal.1.name.de]
long.text = "Volksinitiative «Für eine starke Pflege (Pflegeinitiative)»"
short.text = "Pflegeinitiative"
short.gender = "feminine"
[federal.proposal.1.url]
government = "https://www.admin.ch/gov/de/start/dokumentation/abstimmungen/20211128/pflegeinitiative.html"
proponents = "https://www.pflegeinitiative.ch/"
# [[federal.proposal.1.main_motive.yes]]
# de = "wollte in erster Linie einer bestimmten Abstimmungsempfehlung folgen"
# en = "to follow a specific voting recommendation"
# code = 1
# [[federal.proposal.1.main_motive.yes]]
# de = "TODO"
# en = "TODO"
# code = 2
# [[federal.proposal.1.main_motive.yes]]
# de = "TODO"
# en = "TODO"
# code = 3
# [[federal.proposal.1.main_motive.yes]]
# de = "TODO"
# en = "TODO"
# code = 4
# [[federal.proposal.1.main_motive.yes]]
# de = "TODO"
# en = "TODO"
# code = 5
# [[federal.proposal.1.main_motive.no]]
# de = "wollte in erster Linie einer bestimmten Abstimmungsempfehlung folgen"
# en = "to follow a specific voting recommendation"
# code = 1
# [[federal.proposal.1.main_motive.no]]
# de = "TODO"
# en = "TODO"
# code = 2
# [[federal.proposal.1.main_motive.no]]
# de = "TODO"
# en = "TODO"
# code = 3
# [[federal.proposal.1.main_motive.no]]
# de = "TODO"
# en = "TODO"
# code = 4
# [[federal.proposal.1.main_motive.no]]
# de = "TODO"
# en = "TODO"
# code = 5
# [[federal.proposal.1.main_motive.no]]
# de = "TODO"
# en = "TODO"
# code = 6
# [[federal.proposal.1.argument]]
# de.long = "TODO"
# de.short = "TODO"
# en.long = "TODO"
# side = "pro"
# nr = 1
# [[federal.proposal.1.argument]]
# de.long = "TODO"
# de.short = "TODO"
# en.long = "TODO"
# side = "contra"
# nr = 1
# [[federal.proposal.1.argument]]
# de.long = "TODO"
# de.short = "TODO"
# en.long = "TODO"
# side = "pro"
# nr = 2
# [[federal.proposal.1.argument]]
# de.long = "TODO"
# de.short = "TODO"
# en.long = "TODO"
# side = "contra"
# nr = 2
# [[federal.proposal.1.skill_question]]
# de = "TODO"
# en = "TODO"
# [[federal.proposal.1.skill_question.response_option]]
# de = "TODO"
# en = "TODO"
# is_correct = false # TODO: recheck!
# [[federal.proposal.1.skill_question.response_option]]
# de = "TODO"
# en = "TODO"
# is_correct = false # TODO: recheck!
# [[federal.proposal.1.skill_question.response_option]]
# de = "TODO"
# en = "TODO"
# is_correct = false # TODO: recheck!
# [[federal.proposal.1.skill_question]]
# de = "TODO"
# en = "TODO"
# [[federal.proposal.1.skill_question.response_option]]
# de = "TODO"
# en = "TODO"
# is_correct = false # TODO: recheck!
# [[federal.proposal.1.skill_question.response_option]]
# de = "TODO"
# en = "TODO"
# is_correct = false # TODO: recheck!
# [[federal.proposal.1.skill_question.response_option]]
# de = "TODO"
# en = "TODO"
# is_correct = false # TODO: recheck!
# [[federal.proposal.1.skill_question]]
# de = "TODO"
# en = "TODO"
# [[federal.proposal.1.skill_question.response_option]]
# de = "TODO"
# en = "TODO"
# is_correct = false # TODO: recheck!
# [[federal.proposal.1.skill_question.response_option]]
# de = "TODO"
# en = "TODO"
# is_correct = false # TODO: recheck!
# [[federal.proposal.1.skill_question.response_option]]
# de = "TODO"
# en = "TODO"
# is_correct = false # TODO: recheck!
[federal.proposal.2]
type = "citizens' initiative"
[federal.proposal.2.name.de]
long.text = "Volksinitiative «Bestimmung der Bundesrichterinnen und Bundesrichter im Losverfahren (Justiz-Initiative)»"
short.text = "Justiz-Initiative"
short.gender = "feminine"
[federal.proposal.2.url]
government = "https://www.admin.ch/gov/de/start/dokumentation/abstimmungen/20211128/justiz-initiative.html"
proponents = "https://www.justiz-initiative.ch/"
[[federal.proposal.2.main_motive.yes]]
de = "wollte in erster Linie einer bestimmten Abstimmungsempfehlung folgen"
en = "to follow a specific voting recommendation"
code = 1
[[federal.proposal.2.main_motive.yes]]
de = "wollte ermöglichen, dass parteilose KandidatInnen dieselben Chancen wie Parteimitglieder haben, ans Bundesgericht gewählt zu werden."
en = "TODO"
code = 2
[[federal.proposal.2.main_motive.yes]]
de = "glaube, das bisherige Wahlsystem kann die Unabhängigkeit der BundesrichterInnen nicht gewährleisten."
en = "TODO"
code = 3
[[federal.proposal.2.main_motive.yes]]
de = "bin der Überzeugung, die Verwendung des Loses verhindert eine Bestechung oder anderweitige Beeinflussung der Wahl."
en = "TODO"
code = 4
[[federal.proposal.2.main_motive.yes]]
de = "wollte dafür sorgen, dass BundesrichterInnen keine Angst zu haben brauchen, für politisch unbequeme Urteile abgewählt zu werden."
en = "TODO"
code = 5
[[federal.proposal.2.main_motive.yes]]
de = "habe kein Vertrauen ins Parlament, die besten und fähigsten KandidatInnen ans Bundesgericht zu wählen."
en = "TODO"
code = 6
[[federal.proposal.2.main_motive.no]]
de = "wollte in erster Linie einer bestimmten Abstimmungsempfehlung folgen"
en = "to follow a specific voting recommendation"
code = 1
[[federal.proposal.2.main_motive.no]]
de = "wollte verhindern, dass in Zukunft weitgehend der Zufall über die Wahl der BundesrichterInnen entscheidet."
en = "TODO"
code = 2
[[federal.proposal.2.main_motive.no]]
de = "wollte verhindern, dass sich die BundesrichterInnen nach erfolgreicher Erstwahl keinerlei Wiederwahl mehr stellen müssen."
en = "TODO"
code = 3
[[federal.proposal.2.main_motive.no]]
de = "wollte sicherstellen, dass BundesrichterInnen weiterhin Mitglied einer politschen Partei sind, da dies für Transparenz sorgt."
en = "TODO"
code = 4
[[federal.proposal.2.main_motive.no]]
de = "finde, die Initiative ist zu vage formuliert. Unklar ist vor allem, wie die Fachkommission zustande kommen soll."
en = "TODO"
code = 5
[[federal.proposal.2.main_motive.no]]
de = "vertraue dem Parlament, die besten und fähigsten KandidatInnen ans Bundesgericht zu wählen."
en = "TODO"
code = 6
[[federal.proposal.2.main_motive.no]]
de = "finde das heutige System ganz in Ordnung und sehe keinen Bedarf, etwas daran zu ändern."
en = "TODO"
code = 7
[[federal.proposal.2.argument]]
de.long = "Indem das Parlament alle sechs Jahre über die (Wieder-)Wahl der BundesrichterInnen entscheidet, wird die Gewaltenteilung zwischen Legislative und Judikative verletzt."
de.short = "TODO"
en.long = "TODO"
side = "pro"
nr = 1
[[federal.proposal.2.argument]]
de.long = "Bei der Wahl für ein derart wichtiges Amt wie jenes der BundesrichterInnen etwas dem Zufall zu überlassen (Losziehung), ist unvernünftig."
de.short = "TODO"
en.long = "TODO"
side = "contra"
nr = 1
[[federal.proposal.2.argument]]
de.long = "Dass Bundesrichter-KandidatInnen mit dem heutigen System de facto Parteimitglied sein und sich zur Zahlung einer Mandatssteuer an ihre Partei verpflichten müssen, gefährdet ihre Unabhängigkeit."
de.short = "TODO"
en.long = "TODO"
side = "pro"
nr = 2
[[federal.proposal.2.argument]]
de.long = "Die heute gängige Parteizugehörigkeit der BundesrichterInnen schafft Transparenz über deren politische Gesinnung."
de.short = "TODO"
en.long = "TODO"
side = "contra"
nr = 2
[[federal.proposal.2.skill_question]]
de = "Wer hat bisher die Mitglieder des Bundesgerichts gewählt?"
en = "TODO"
[[federal.proposal.2.skill_question.response_option]]
de = "Der Bundesrat"
en = "TODO"
is_correct = false
[[federal.proposal.2.skill_question.response_option]]
de = "Die Bundesversammlung"
en = "TODO"
is_correct = true
[[federal.proposal.2.skill_question.response_option]]
de = "Das Bundesgericht selbst"
en = "TODO"
is_correct = false
[[federal.proposal.2.skill_question.response_option]]
de = "Das Volk"
en = "TODO"
is_correct = false
[[federal.proposal.2.skill_question]]
de = "Die Justiz-Initiative verlangt, dass in Zukunft…"
en = "TODO"
[[federal.proposal.2.skill_question.response_option]]
de = "BundesrichterInnen keiner Partei mehr angehören dürfen."
en = "TODO"
is_correct = false
[[federal.proposal.2.skill_question.response_option]]
de = "ein Zufallsverfahren über die Wahl fachlich und persönlich geeigneter KandidatInnen entscheidet."
en = "TODO"
is_correct = true
[[federal.proposal.2.skill_question.response_option]]
de = "BundesrichterInnen zur Gewährleistung ihrer eigenen Sicherheit in Ausnahmefällen anonyme Entscheide fällen dürfen (bspw. Prozesse im Bereich organisierter Kriminalität)."
en = "TODO"
is_correct = false
[[federal.proposal.2.skill_question]]
de = "Das heutige Wahlverfahren der BundesrichterInnen stellt sicher, dass…"
en = "TODO"
[[federal.proposal.2.skill_question.response_option]]
de = "…die unterschiedlichen Geschlechter, politischen Gesinnungen und Amtssprachen allesamt gleichmässig vertreten sind."
en = "TODO"
is_correct = false
[[federal.proposal.2.skill_question.response_option]]
de = "…die KandidatInnen keinerlei Parteibindungen aufweisen müssen, um gewählt zu werden."
en = "TODO"
is_correct = false
[[federal.proposal.2.skill_question.response_option]]
de = "…die KandidatInnen alle dieselbe Chance haben, gewählt zu werden."
en = "TODO"
is_correct = false
[[federal.proposal.2.skill_question.response_option]]
de = "…sich die AmtinhaberInnen alle sechs Jahre der Wiederwahl stellen müssen."
en = "TODO"
is_correct = true
[federal.proposal.3]
type = "optional referendum"
[federal.proposal.3.name.de]
long.text = "Änderung vom 19. März 2021 des Bundesgesetzes über die gesetzlichen Grundlagen für Verordnungen des Bundesrates zur Bewältigung der Covid-19-Epidemie"
short.text = "Covid-19-Gesetz"
short.gender = "neuter"
[federal.proposal.3.url]
government = "https://www.admin.ch/gov/de/start/dokumentation/abstimmungen/20211128/aenderung-vom-19-maerz-2021-des-covid-19-gesetzes.html"
opponents = "https://covidgesetz-nein.ch/"
[[federal.proposal.3.main_motive.yes]]
de = "wollte in erster Linie einer bestimmten Abstimmungsempfehlung folgen"
en = "to follow a specific voting recommendation"
code = 1
[[federal.proposal.3.main_motive.yes]]
de = "wollte zusätzliche Finanzhilfen des Staates an krisengebeutelte Unternehmen und Selbständige nicht gefährden."
en = "TODO"
code = 2
[[federal.proposal.3.main_motive.yes]]
de = "befürworte die Covid-Zertifikatspflicht und wollte das Leben für Geimpfte erleichtern (Veranstaltungen, Auslandsreisen etc.)."
en = "TODO"
code = 3
[[federal.proposal.3.main_motive.yes]]
de = "glaube, dass die Covid-Zertifikatspflicht zur Impfung motiviert und dies der wirkungsvollste Weg ist, die Pandemie zu beenden."
en = "TODO"
code = 4
[[federal.proposal.3.main_motive.yes]]
de = "wollte eine weitere Spaltung der Schweizer Gesellschaft verhindern."
en = "TODO"
code = 5
[[federal.proposal.3.main_motive.yes]]
de = "wollte ein Zeichen setzen gegen MassnahmengegnerInnen und/oder ImpfskeptikerInnen."
en = "TODO"
code = 6
[[federal.proposal.3.main_motive.yes]]
de = "wollte, dass der Bund endlich die Kompetenz erhält, ein funktionierendes, schweizweites Contact-Tracing-System aufzubauen."
en = "TODO"
code = 7
[[federal.proposal.3.main_motive.no]]
de = "wollte in erster Linie einer bestimmten Abstimmungsempfehlung folgen"
en = "to follow a specific voting recommendation"
code = 1
[[federal.proposal.3.main_motive.no]]
de = "wollte die Covid-Zertifikatspflicht rückgängig machen."
en = "TODO"
code = 2
[[federal.proposal.3.main_motive.no]]
de = "wollte einen indirekten Impfzwang durch die Covid-Zertifikatspflicht verhindern."
en = "TODO"
code = 3
[[federal.proposal.3.main_motive.no]]
de = "wollte eine Diskriminierung Ungeimpfter verhindern."
en = "TODO"
code = 4
[[federal.proposal.3.main_motive.no]]
de = "wollte eine weitere Spaltung der Schweizer Gesellschaft verhindern."
en = "TODO"
code = 5
[[federal.proposal.3.main_motive.no]]
de = "wollte zusätzliche Finanzhilfen des Staates an Unternehmen und Selbständige verhindern."
en = "TODO"
code = 6
[[federal.proposal.3.main_motive.no]]
de = "wollte eine elektronische Massenüberwachung durch ein schweizweites digitales Contact-Tracing verhindern."
en = "TODO"
code = 7
[[federal.proposal.3.main_motive.no]]
de = "wollte eine Machtausweitung des Bundesrates verhindern."
en = "TODO"
code = 8
[[federal.proposal.3.main_motive.no]]
de = "wollte ein Zeichen setzen gegen MassnahmenbefürworterInnen und/oder ImpfbefürworterInnen."
en = "TODO"
code = 9
[[federal.proposal.3.argument]]
de.long = "Das Covid-19-Gesetz ermöglicht dem Staat mittels Ausweitung der finanziellen Hilfsprogramme einen grösseren Teil der Schweizer Wirtschaft heil durch die Krise zu bringen."
de.short = "TODO"
en.long = "TODO"
side = "pro"
nr = 1
[[federal.proposal.3.argument]]
de.long = "Ungeimpfte werden durch neue Massnahmen des Covid-19-Gesetzes wie die Zertifikatspflicht diskriminiert."
de.short = "TODO"
en.long = "TODO"
side = "contra"
nr = 1
[[federal.proposal.3.argument]]
de.long = "Die im Covid-19-Gesetz vorgesehene Zertifikatspflicht ist verhältnismässig, da sie eine Normalisierung des wirtschaftlichen und gesellschaftlichen Lebens ermöglicht, ohne das Gesundheitswesen unnötig zu belasten."
de.short = "TODO"
en.long = "TODO"
side = "pro"
nr = 2
[[federal.proposal.3.argument]]
de.long = "Der Bundesrat erhält zu viel Macht, indem er eigenmächtig Kriterien und Richtwerte für Einschränkungen und Erleichterungen festlegen kann."
de.short = "TODO"
en.long = "TODO"
side = "contra"
nr = 2
[[federal.proposal.3.skill_question]]
de = "Wann treten die Änderungen des Covid-19-Gesetzes, über die jetzt abgestimmt werden, in Kraft?"
en = "TODO"
[[federal.proposal.3.skill_question.response_option]]
de = "Sie sind bereits in Kraft."
en = "TODO"
is_correct = true
[[federal.proposal.3.skill_question.response_option]]
de = "Sie treten/traten am Abstimmungssonntag vom 28. November 2021 in Kraft."
en = "TODO"
is_correct = false
[[federal.proposal.3.skill_question.response_option]]
de = "Sie treten einen Monat nach dem Abstimmungstermin in Kraft."
en = "TODO"
is_correct = false
[[federal.proposal.3.skill_question.response_option]]
de = "Sie treten am 1. Januar 2022 in Kraft."
en = "TODO"
is_correct = false
[[federal.proposal.3.skill_question]]
de = "Was wird durch ein gültiges Schweizer Covid-Zertifikat nachgewiesen? Dass die entsprechende Person…"
en = "TODO"
[[federal.proposal.3.skill_question.response_option]]
de = "…gegen COVID-19 geimpft ist."
en = "TODO"
is_correct = false
[[federal.proposal.3.skill_question.response_option]]
de = "…gegen COVID-19 geimpft ist oder sich für eine bestimmte Dauer in Quarantäne begeben hat."
en = "TODO"
is_correct = false
[[federal.proposal.3.skill_question.response_option]]
de = "…gegen COVID-19 geimpft oder negativ getestet ist."
en = "TODO"
is_correct = false
[[federal.proposal.3.skill_question.response_option]]
de = "…gegen COVID-19 geimpft, negativ getestet oder davon genesen ist."
en = "TODO"
is_correct = true
[[federal.proposal.3.skill_question]]
de = "Was geschieht im Falle einer Ablehnung des geänderten Covid-19-Gesetzes?"
en = "TODO"
[[federal.proposal.3.skill_question.response_option]]
de = "Alle Pandemiemassnahmen des Bundes werden aufgehoben und stattdessen erhalten die Kantone zusätzliche Kompetenzen in der Pandemiebekämpfung."
en = "TODO"
is_correct = false
[[federal.proposal.3.skill_question.response_option]]
de = "Diejenigen Bestimmungen/Änderungen, welche die Bundesversammlung am 19. März 2021 verabschiedete, treten _sofort_ ausser Kraft."
en = "TODO"
is_correct = false
[[federal.proposal.3.skill_question.response_option]]
de = "Diejenigen Bestimmungen/Änderungen, welche die Bundesversammlung am 19. März 2021 verabschiedete, treten _am 19. März 2022_ ausser Kraft."
en = "TODO"
is_correct = true
[[federal.proposal.3.skill_question.response_option]]
de = "Das gesamte Covid-19-Gesetz tritt bis spätestens Ende Jahr ausser Kraft."
en = "TODO"
is_correct = false
